### ISSUE TITLE
당신의 코드 흥미롭다. 잘 보고 있다.

### ISSUE THREAD

**Issue by 97Kzone** [cksghks89/spring-practices#2]
트랜잭션 흥미롭다. 몰랐다. 있는 줄
궁금하다. 동시성과 잠금이 중요한 뱅킹 시스템
선언형 @Transcation 프로그래밍적인 TransactionManager
무엇이 더 적합한가.
원한다. 당신의 대답 난 검색하기 귀찮다

**Comment by cksghks89** [comment]
@Transactional 이 훨씬 좋다. 간편하고.
다만, 알아야 한다. 내부동작과 구조.
그 과정을 이해하기 위함이다. 지금 코드는.
